# These are supported funding model platforms

github: CTWR-Org
patreon: # Replace with Patreon username
open_collective: # Replace with Open Collective name
ko_fi: # Replace with Ko-fi username
tidelift: # Replace with Tidelift platform-name/package-name
community_bridge: # Replace with Community Bridge project-name
liberapay: # Replace with Liberapay username
issuehunt: # Replace with IssueHunt username
otechie: # Replace with Otechie username
custom: # Replace with up to 4 custom sponsorship URLs
  - https://www.meetup.com/civictechwr/
