# Security Configuration for CTWR Website
# This file contains security headers and CSP policies

# Content Security Policy
csp:
  default-src: "'self'"
  script-src: "'self' 'unsafe-inline' 'unsafe-eval' https://code.jquery.com https://cdn.jsdelivr.net"
  style-src: "'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com"
  font-src: "'self' https://fonts.gstatic.com https://cdn.jsdelivr.net"
  img-src: "'self' data: https:"
  connect-src: "'self'"
  frame-src: "'none'"
  object-src: "'none'"
  base-uri: "'self'"
  form-action: "'self'"
  frame-ancestors: "'none'"

# Security Headers
security_headers:
  X-Content-Type-Options: "nosniff"
  X-Frame-Options: "DENY"
  X-XSS-Protection: "1; mode=block"
  Referrer-Policy: "strict-origin-when-cross-origin"
  Permissions-Policy: "camera=(), microphone=(), geolocation=()"
  Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"

# Additional Security Settings
security:
  # Disable directory browsing
  directory_browsing: false
  
  # Enable HTTPS redirect
  https_redirect: true
  
  # Disable server signature
  server_signature: false
