module.exports = {
  content: [
    './**/*.html',
    './**/*.js',
    './_includes/**/*.html',
    './_layouts/**/*.html',
    './_data/**/*.yml',
    './_data/**/*.yaml',
    './_data/**/*.json'
  ],
  css: [
    './css/**/*.css'
  ],
  output: './css/purged/',
  safelist: [
    /^btn--/,
    /^shape-/,
    /^abstract-/,
    /^navbar/,
    /^hero/,
    /^footer/,
    /^section/,
    /^container/,
    /^row/,
    /^col/,
    /^mt-/,
    /^mb-/,
    /^p-/,
    /^text-/,
    /^align/,
    /^justify/,
    /^d-/,
    /^flex/,
    /^grid/,
    /^position/,
    /^top-/,
    /^left-/,
    /^right-/,
    /^bottom-/,
    /^w-/,
    /^h-/,
    /^max-/,
    /^min-/,
    /^overflow/,
    /^border/,
    /^rounded/,
    /^shadow/,
    /^opacity/,
    /^z-/,
    /^transform/,
    /^transition/,
    /^animate/,
    /^hover/,
    /^focus/,
    /^active/,
    /^disabled/,
    /^sr-only/,
    /^skip-link/,
    /^is-sticky/,
    /^has-fixed-nav/,
    /^site-header/,
    /^page-title/,
    /^page-subtitle/,
    /^projects-/,
    /^meeting-/,
    /^organizer-/,
    /^shoutout-/,
    /^custom-/,
    /^form-/,
    /^floating/,
    /^img-/,
    /^fluid/,
    /^responsive/,
    /^mobile/,
    /^tablet/,
    /^desktop/,
    /^avatar-/,
    /^preloader/,
    /^spinner/,
    /^icon/,
    /^featured-/,
    /^sponsors-/,
    /^projects-/,
    /^contact-/,
    /^profile-/,
    /^about-/,
    /^site-header/,
    /^page-/,
    /^footer-col/
  ],
  defaultExtractor: content => {
    const broadMatches = content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || []
    const innerMatches = content.match(/[^<>"'`\s.()]*[^<>"'`\s.():]/g) || []
    return broadMatches.concat(innerMatches)
  }
}
