name: Accessibility

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  pa11y:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run Pa11y CI against built site
        run: |
          npx --yes http-server _site -p 4000 &
          SERVER_PID=$!
          trap "kill $SERVER_PID" EXIT
          sleep 2
          npx --yes pa11y-ci --config .pa11yci.json
