name: Accessibility

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  pa11y:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Build site
        run: |
          bundle exec jekyll build
          echo "Build completed successfully"
          ls -la _site/

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: "20"

      - name: Run Pa11y CI against built site
        run: |
          echo "Starting http-server on port 4000..."
          npx --yes http-server _site -p 4000 &
          SERVER_PID=$!
          trap "kill $SERVER_PID" EXIT
          sleep 5
          echo "Testing server connectivity..."
          curl -I http://127.0.0.1:4000/ || echo "Server not responding"
          echo "Running pa11y-ci..."
          npx --yes pa11y-ci --config .pa11yci.json
